{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "import cv2\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import math\n",
    "import os\n",
    "from shutil import copyfile\n",
    "from tensorflow import keras"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Num GPU:  0\n"
     ]
    }
   ],
   "source": [
    "print(\"Num GPU: \", len(tf.config.experimental.list_physical_devices(\"GPU\")))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "False\n",
      "False\n"
     ]
    }
   ],
   "source": [
    "print(tf.test.is_gpu_available())\n",
    "print(tf.test.is_built_with_cuda())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2.1.0\n"
     ]
    }
   ],
   "source": [
    "print(tf.version.VERSION)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]'"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import sys \n",
    "sys.version"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "#load one picture and display it\n",
    "original = cv2.imread('images_sudoku/sudoku0.JPG')\n",
    "cv2.imshow('original', original)\n",
    "\n",
    "#make copy for configuration, resize it too, 809 bec of dividing later with 9 \n",
    "IMAGE_SIZE = (809,809)\n",
    "original_copy = cv2.resize(original.copy(), IMAGE_SIZE)\n",
    "\n",
    "cv2.waitKey(0)\n",
    "cv2.destroyAllWindows()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "#preprocess image function\n",
    "def preprocessing_image(img):\n",
    "    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
    "    #eliminates noises in pictures\n",
    "    blur = cv2.GaussianBlur(gray, (5,5), 1)\n",
    "    #select areas of an image, while ignoring the parts we are not concerned with\n",
    "    treshhold = cv2.adaptiveThreshold(blur,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV,11,3)\n",
    "    return treshhold\n",
    "\n",
    "#display image function\n",
    "def display_image(img):\n",
    "    cv2.imshow(\"image\", img)\n",
    "    cv2.waitKey(0)\n",
    "    cv2.destroyAllWindows()\n",
    "\n",
    "pre_image = preprocessing_image(original_copy)\n",
    "display_image(pre_image)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-8-738a7d26d9db>\", line 9, in <module>\n",
      "    cont_image = find_contours(pre_image)\n",
      "  File \"<ipython-input-8-738a7d26d9db>\", line 4, in find_contours\n",
      "    contours, hierarchy = cv2.findContours(image=pre_image, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)\n",
      "ValueError: too many values to unpack (expected 2)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-8-738a7d26d9db>\", line 9, in <module>\n",
      "    cont_image = find_contours(pre_image)\n",
      "  File \"<ipython-input-8-738a7d26d9db>\", line 4, in find_contours\n",
      "    contours, hierarchy = cv2.findContours(image=pre_image, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)\n",
      "ValueError: too many values to unpack (expected 2)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-8-738a7d26d9db>\", line 9, in <module>\n",
      "    cont_image = find_contours(pre_image)\n",
      "  File \"<ipython-input-8-738a7d26d9db>\", line 4, in find_contours\n",
      "    contours, hierarchy = cv2.findContours(image=pre_image, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)\n",
      "ValueError: too many values to unpack (expected 2)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 1490, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 1448, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\tensorflow\\__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\site-packages\\tensorflow\\__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"C:\\Users\\zjuli\\anaconda3\\envs\\tensorflow_env\\lib\\importlib\\__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 953, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    }
   ],
   "source": [
    "#define contours function\n",
    "def find_contours(pre_image): \n",
    "    #find only external contours\n",
    "    contours, hierarchy = cv2.findContours(image=pre_image, mode=cv2.RETR_EXTERNAL, method=cv2.CHAIN_APPROX_SIMPLE)\n",
    "    #draw contours in image\n",
    "    image_contours = cv2.drawContours(image=original_copy, contours=contours, contourIdx=-1, color=(0, 255, 0), thickness=2, lineType=cv2.LINE_AA)\n",
    "    return image_contours\n",
    "\n",
    "cont_image = find_contours(pre_image)\n",
    "display_image(cont_image)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#find corners of sudoku square\n",
    "def find_contours(img):\n",
    "    #get only \"outer\" contours with RETR_EXTERNAL\n",
    "    #ContourArea finds area of outermost polygon(largest feature) in img\n",
    "    ext_contours = cv2.findContours(img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n",
    "    ext_contours = ext_contours[0] if len(ext_contours) == 2 else ext_contours[1]\n",
    "    ext_contours = sorted(ext_contours, key=cv2.contourArea, reverse=True)\n",
    "\n",
    "    for c in ext_contours:\n",
    "        peri = cv2.arcLength(c, True)\n",
    "        #Approximates a polygonal curve(s) with the specified precision\n",
    "        approx = cv2.approxPolyDP(c, 0.015 * peri, True)\n",
    "        if len(approx) == 4:\n",
    "            #looking for the largest 4 sided contour\n",
    "            return approx\n",
    "\n",
    "\n",
    "#define order of corners \n",
    "def order_corner_points(corners):\n",
    "    #Corners[0],... stores in format [[x y]]\n",
    "    #Separate corners into individual points\n",
    "    #Index 0 - top-right\n",
    "    #      1 - top-left\n",
    "    #      2 - bottom-left\n",
    "    #      3 - bottom-right\n",
    "    corners = [(corner[0][0], corner[0][1]) for corner in corners]\n",
    "    top_r, top_l, bottom_l, bottom_r = corners[0], corners[1], corners[2], corners[3]\n",
    "    return top_l, top_r, bottom_r, bottom_l\n",
    "\n",
    "\n",
    "#delete unnecessary background, so only the sudoku grid is in the picture\n",
    "def perspective_transform(image, corners): \n",
    "    #Order points in clockwise order\n",
    "    ordered_corners = order_corner_points(corners)\n",
    "    top_l, top_r, bottom_r, bottom_l = ordered_corners\n",
    "\n",
    "    #Determine width of new image which is the max distance between\n",
    "    #(bottom right and bottom left) or (top right and top left) x-coordinates\n",
    "    width_A = np.sqrt(((bottom_r[0] - bottom_l[0]) ** 2) + ((bottom_r[1] - bottom_l[1]) ** 2))\n",
    "    width_B = np.sqrt(((top_r[0] - top_l[0]) ** 2) + ((top_r[1] - top_l[1]) ** 2))\n",
    "    width = max(int(width_A), int(width_B))\n",
    "\n",
    "    #Determine height of new image which is the max distance between\n",
    "    #(top right and bottom right) or (top left and bottom left) y-coordinates\n",
    "    height_A = np.sqrt(((top_r[0] - bottom_r[0]) ** 2) + ((top_r[1] - bottom_r[1]) ** 2))\n",
    "    height_B = np.sqrt(((top_l[0] - bottom_l[0]) ** 2) + ((top_l[1] - bottom_l[1]) ** 2))\n",
    "    height = max(int(height_A), int(height_B))\n",
    "\n",
    "    #Construct new points to obtain top-down view of image in\n",
    "    #top_r, top_l, bottom_l, bottom_r order\n",
    "    dimensions = np.array([[0, 0], [width - 1, 0], [width - 1, height - 1],\n",
    "                           [0, height - 1]], dtype=\"float32\")\n",
    "\n",
    "    #convert to numpy array\n",
    "    ordered_corners = np.array(ordered_corners, dtype=\"float32\")\n",
    "\n",
    "    #calculate the perspective transform matrix and warp\n",
    "    #the perspective to grab the screen\n",
    "    grid = cv2.getPerspectiveTransform(ordered_corners, dimensions)\n",
    "\n",
    "    return cv2.warpPerspective(image, grid, (width, height))\n",
    "\n",
    "#checking corners coordinates\n",
    "contours = find_contours(pre_image)\n",
    "ordered_corners = order_corner_points(contours)\n",
    "\n",
    "#plot red corners\n",
    "for direction in ordered_corners:\n",
    "    image_corner = cv2.circle(original_copy, direction, radius=3, color=(0,0,255), thickness=cv2.FILLED)\n",
    "\n",
    "display_image(image_corner) \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#checking transformed image\n",
    "trans_image = perspective_transform(original_copy, contours)\n",
    "display_image(trans_image)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#plot gray scaled\n",
    "trans_original = perspective_transform(cv2.resize(original, IMAGE_SIZE), contours)\n",
    "trans_gray = preprocessing_image(trans_original)\n",
    "\n",
    "#resize it to 809,809 for better division\n",
    "trans_gray_resized = cv2.resize(trans_gray, IMAGE_SIZE)\n",
    "\n",
    "display_image(trans_gray_resized)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "COLUMNS = ROWS = 9\n",
    "WIDTH = HEIGHT = 0 \n",
    "\n",
    "#create 9x9 matrix\n",
    "matrix = [[0 for x in range(COLUMNS)] for y in range(ROWS)]\n",
    "\n",
    "#iterate through matrix and split sudoku image in 81 images\n",
    "for x in range(COLUMNS):   \n",
    "    WIDTH = 0\n",
    "    for y in range(ROWS):\n",
    "        matrix[x][y] = (trans_gray_resized[HEIGHT:(HEIGHT+90)-1,WIDTH:(WIDTH+90)-1])\n",
    "        WIDTH = WIDTH + 90\n",
    "        y = y + 1\n",
    "    x = x + 1\n",
    "    HEIGHT = HEIGHT + 90\n",
    "    \n",
    "#print(matrix)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#function to plot 9x9 matrix\n",
    "def plotmatrix(NULL):\n",
    "    plt.figure(figsize=(10,10))\n",
    "\n",
    "    #adjust subplot so you can see all subplots \n",
    "    plt.subplots_adjust(left=0.1,\n",
    "                        bottom=0.1, \n",
    "                        right=1, \n",
    "                        top=1, \n",
    "                        wspace=0.25, \n",
    "                        hspace=0.5)\n",
    "\n",
    "    #iterate through all arrays and print them as subplot\n",
    "    it_sub = 0\n",
    "    for x in range(COLUMNS):\n",
    "        for y in range(ROWS):\n",
    "            plt.subplot(9, 9, it_sub + 1)\n",
    "            plt.imshow(matrix[x][y])   \n",
    "            y = y + 1\n",
    "            it_sub = it_sub + 1\n",
    "        x = x + 1\n",
    "    \n",
    "    plt.show\n",
    "\n",
    "plotmatrix(0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#get ride off the girds in images\n",
    "def cutgrid(matrix):\n",
    "    for x in range(COLUMNS):\n",
    "        for y in range(ROWS):\n",
    "            image = matrix[x][y]\n",
    "            image = image[10:80,10:80]\n",
    "            matrix[x][y] = image\n",
    "\n",
    "cutgrid(matrix)\n",
    "plotmatrix(0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#create train and test directories\n",
    "if not os.path.isdir('dataset'):\n",
    "  os.mkdir('dataset')\n",
    "if not os.path.isdir('dataset/training'):\n",
    "  os.mkdir('dataset/training')\n",
    "if not os.path.isdir('dataset/testing'):\n",
    "  os.mkdir('dataset/testing')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#make class directories inside them\n",
    "for i in sorted(os.listdir('all_data')):\n",
    "  if not os.path.isdir('dataset/training/'+i):\n",
    "    os.mkdir('dataset/training/'+i)\n",
    "  if not os.path.isdir('dataset/testing/'+i):\n",
    "    os.mkdir('dataset/testing/'+i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#copy random images to training or testing folder\n",
    "base = 'all_data/number_'\n",
    "\n",
    "for char in range(0, 10):\n",
    "  classLen = len(os.listdir(base + str(char)))\n",
    "\n",
    "  trainLen = math.floor(classLen*0.80)\n",
    "\n",
    "  randFnt = np.random.randint(low = 1, high = classLen, size = classLen)\n",
    "  randTrain = randFnt[:trainLen]\n",
    "  randTest = randFnt[trainLen:]\n",
    "\n",
    "  for imgNo in randTrain:\n",
    "    src = base+str(char)+'/img'+str(char+1).zfill(3)+'-'+str(imgNo).zfill(5)+'.png'\n",
    "    des = 'dataset/training/number_'+str(char)+'/img'+str(char+1).zfill(3)+'-'+str(imgNo).zfill(5)+'.png'\n",
    "    copyfile(src, des)\n",
    "\n",
    "  for imgNo in randTest:\n",
    "    src = base+str(char)+'/img'+str(char+1).zfill(3)+'-'+str(imgNo).zfill(5)+'.png'\n",
    "    des = 'dataset/testing/number_'+str(char)+'/img'+str(char+1).zfill(3)+'-'+str(imgNo).zfill(5)+'.png'\n",
    "    copyfile(src, des)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#define constants\n",
    "num_classes = 10\n",
    "image_resize = 128\n",
    "num_epochs = 12\n",
    "batch_size = 64"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import keras\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense \n",
    "\n",
    "from keras.preprocessing.image import ImageDataGenerator\n",
    "\n",
    "from keras.models import load_model\n",
    "\n",
    "from keras.layers.convolutional import Conv2D\n",
    "from keras.layers.convolutional import MaxPooling2D\n",
    "\n",
    "from keras.layers import Flatten"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#create data generator\n",
    "data_generator = ImageDataGenerator(rescale=1.0/255.0,\n",
    "                                    validation_split=0.2,\n",
    "                                    zoom_range=0.2,\n",
    "                                    width_shift_range=20,\n",
    "                                    height_shift_range=10,\n",
    "                                    brightness_range=[0.3,0.9])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#create train and valid generators\n",
    "train_dir = \"dataset/training\"\n",
    "\n",
    "train_generator = data_generator.flow_from_directory(\n",
    "    train_dir,\n",
    "    target_size = (image_resize, image_resize),\n",
    "    batch_size=batch_size,\n",
    "    color_mode = 'grayscale',\n",
    "    class_mode = 'categorical',\n",
    "    subset= \"training\"\n",
    ")\n",
    "\n",
    "validation_generator = data_generator.flow_from_directory(\n",
    "    train_dir,\n",
    "    target_size = (image_resize, image_resize),\n",
    "    batch_size=batch_size,\n",
    "    color_mode = 'grayscale',\n",
    "    class_mode = 'categorical',\n",
    "    subset= \"validation\"\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#create the model\n",
    "model = Sequential()\n",
    "model.add(Conv2D(32, (4,4), strides = (1,1), activation = 'relu', input_shape = (128, 128, 1)))\n",
    "model.add(MaxPooling2D(pool_size = (4,4), strides = (2,2)))\n",
    "model.add(Conv2D(64, (4,4), strides = (1,1), activation = 'relu'))\n",
    "model.add(MaxPooling2D(pool_size = (4,4),strides = (2,2)))\n",
    "model.add(Flatten())\n",
    "model.add(Dense(64, activation='relu'))\n",
    "model.add(Dense(num_classes, activation = 'softmax'))\n",
    "model.compile(optimizer = 'adam',loss = 'categorical_crossentropy',metrics = ['accuracy'])\n",
    "\n",
    "\n",
    "#view model summary\n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "history = model.fit(\n",
    "    train_generator,\n",
    "    steps_per_epoch= train_generator.samples//batch_size,\n",
    "    validation_data = validation_generator,\n",
    "    validation_steps = validation_generator.samples // batch_size,\n",
    "    epochs = num_epochs,\n",
    "    verbose = 1\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#save the model\n",
    "model.save(\"sudoku.h5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#load model if you already \n",
    "model = tf.keras.models.load_model(\"sudoku.h5\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#checking accuracy depending on epochs\n",
    "plt.plot(range(1,13), history.history['val_accuracy'], label='valid')\n",
    "plt.plot(range(1,13), history.history['accuracy'], label='train')\n",
    "plt.xlabel('epochs')\n",
    "plt.ylabel('accuracy')\n",
    "plt.legend()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#create test genrator for evalution\n",
    "test_generator = data_generator.flow_from_directory(\n",
    "    'dataset/testing',\n",
    "    target_size = (image_resize, image_resize),\n",
    "    shuffle = False,\n",
    "    color_mode='grayscale'\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#evalute model on test data\n",
    "eva = model.evaluate(test_generator, verbose=1)\n",
    "print('Model performance:')\n",
    "print('loss for test dataset is : {}'.format(eva[0]))\n",
    "print('accuracy for test dataset is : {}'.format(eva[1]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# #with this function I looked for a suitable constant for seperating between an empty image and an image with number\n",
    "# for x in range(COLUMNS):\n",
    "#         for y in range(ROWS):\n",
    "#             image = matrix[x][y] \n",
    "#             #image = cv2.bitwise_not(image) \n",
    "#             print(np.count_nonzero(image), \"-------\",x , \"-------\",y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#function that counts pixel in image to difference between blank image and image with number\n",
    "def numericallysudoku(matrix):\n",
    "    for x in range(COLUMNS):\n",
    "        for y in range(ROWS):\n",
    "            image = matrix[x][y]      \n",
    "            #count zeros to differate between image with number and without\n",
    "            if (np.count_nonzero(image)>300):\n",
    "                image = cv2.bitwise_not(image)     \n",
    "                image = cv2.resize(image, (128,128))\n",
    "                #configurate image format for prediction\n",
    "                image = image.astype('float32')\n",
    "                image = image.reshape(1, 128, 128, 1)\n",
    "                image /= 255\n",
    "                #prediction \n",
    "                pred = model.predict(image)\n",
    "                matrix[x][y] = pred.argmax()\n",
    "            else:\n",
    "                matrix[x][y] = 0\n",
    "                \n",
    "numericallysudoku(matrix) \n",
    "\n",
    "#print predicted values\n",
    "print (matrix)\n",
    "\n",
    "#compare output with image\n",
    "display_image(trans_gray_resized)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#code from (https://github.com/techwithtim/Sudoku-GUI-Solver/blob/master/solver%20(text).py)\n",
    "#code credits to techwithtim\n",
    "\n",
    "#backtracking algorithm for solving sudoku\n",
    "\n",
    "def solve(bo):\n",
    "    \"\"\"\n",
    "    Solves a sudoku board using backtracking\n",
    "    :param bo: 2d list of ints\n",
    "    :return: solution\n",
    "    \"\"\"\n",
    "    find = find_empty(bo)\n",
    "    if find:\n",
    "        row, col = find\n",
    "    else:\n",
    "        return True\n",
    "\n",
    "    for i in range(1,10):\n",
    "        if valid(bo, (row, col), i):\n",
    "            bo[row][col] = i\n",
    "\n",
    "            if solve(bo):\n",
    "                return True\n",
    "\n",
    "            bo[row][col] = 0\n",
    "\n",
    "    return False\n",
    "\n",
    "\n",
    "def valid(bo, pos, num):\n",
    "    \"\"\"\n",
    "    Returns if the attempted move is valid\n",
    "    :param bo: 2d list of ints\n",
    "    :param pos: (row, col)\n",
    "    :param num: int\n",
    "    :return: bool\n",
    "    \"\"\"\n",
    "\n",
    "    # Check row\n",
    "    for i in range(0, len(bo)):\n",
    "        if bo[pos[0]][i] == num and pos[1] != i:\n",
    "            return False\n",
    "\n",
    "    # Check Col\n",
    "    for i in range(0, len(bo)):\n",
    "        if bo[i][pos[1]] == num and pos[1] != i:\n",
    "            return False\n",
    "\n",
    "    # Check box\n",
    "\n",
    "    box_x = pos[1]//3\n",
    "    box_y = pos[0]//3\n",
    "\n",
    "    for i in range(box_y*3, box_y*3 + 3):\n",
    "        for j in range(box_x*3, box_x*3 + 3):\n",
    "            if bo[i][j] == num and (i,j) != pos:\n",
    "                return False\n",
    "\n",
    "    return True\n",
    "\n",
    "\n",
    "def find_empty(bo):\n",
    "    \"\"\"\n",
    "    finds an empty space in the board\n",
    "    :param bo: partially complete board\n",
    "    :return: (int, int) row col\n",
    "    \"\"\"\n",
    "\n",
    "    for i in range(len(bo)):\n",
    "        for j in range(len(bo[0])):\n",
    "            if bo[i][j] == 0:\n",
    "                return (i, j)\n",
    "\n",
    "    return None\n",
    "\n",
    "\n",
    "def print_board(bo):\n",
    "    \"\"\"\n",
    "    prints the board\n",
    "    :param bo: 2d List of ints\n",
    "    :return: None\n",
    "    \"\"\"\n",
    "    for i in range(len(bo)):\n",
    "        if i % 3 == 0 and i != 0:\n",
    "            print(\"- - - - - - - - - - - - - -\")\n",
    "        for j in range(len(bo[0])):\n",
    "            if j % 3 == 0:\n",
    "                print(\" | \",end=\"\")\n",
    "\n",
    "            if j == 8:\n",
    "                print(bo[i][j], end=\"\\n\")\n",
    "            else:\n",
    "                print(str(bo[i][j]) + \" \", end=\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "solve(matrix)\n",
    "print_board(matrix)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "5c400b65cd6b4a666898f9d49c9de859aa773610206038f1b25d58a7803b77b1"
  },
  "kernelspec": {
   "display_name": "Python 3.6.13 64-bit ('tensorflow_env': conda)",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
